networks:
  demo:
    driver: bridge
services:
  migrate:
    build: .
    image: sangdev2109/cat-migrate:latest
    command: npx sequelize-cli db:migrate --config dist/config/config.json --env development 
    container_name: cat-migrate
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - demo
    environment:
      - NODE_ENV=production
  app:
    build: .
    image: sangdev2109/cat-app:latest
    container_name: cat
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - OTP_TOKEN_SECRET=${OTP_TOKEN_SECRET}
      - SMTP_PASS=${SMTP_PASS}
      - NODE_ENV=production
      - REDIS_HOST=${REDIS_HOST}
      - PORT=${PORT}
    ports: 
      - "80:80"
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    networks:
      - demo
 
  postgres:
    image: postgres:17
    networks:
      - demo
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sangduong
      POSTGRES_DB: cat
      POSTGRES_PASSWORD: 210919
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sangduong -d cat"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis/redis-stack
    container_name: redis
    networks:
      - demo
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data

  
volumes:
  postgres_data: null 
  pgadmin_data: null
  redis_data: null

