networks:
  demo:
    driver: bridge
    external: true
services:
  # api-gateway:
  #   image: my-app/api-gateway:1.0
  #   depends_on:
  #     - user-service
  #     - auth-service

  # user-service:
  #   image: my-app/user-service:1.0
  #   depends_on:
  #       - postgres

  # auth-service:
  #   image: my-app/auth-service:1.0
  #   depends_on:
  #       - postgres
  #       # - redis

  postgres:
    # conrtainer_name: nestjs1
    image: postgres:17
    networks:
      - demo
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sangduong
      POSTGRES_DB: cat
      POSTGRES_PASSWORD: 210919
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sangduong -d cat"]
      interval: 10s
      timeout: 5s
      retries: 5


  pgadmin:
    container_name: pg_admin4
    image: dpage/pgadmin4
    networks:
      - demo
    restart: always
    ports:
      - "5050:8000"
    environment:
      PGADMIN_DEFAULT_EMAIL: sangdev219@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: 210919
    depends_on:
      postgres:
          condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin 


  nestjs:
    # conrtainer_name: nestjs3
    image: nestjs:latest
    build: .
    networks:
      - demo
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: sangduong
      DB_PASS: 210919
      DB_NAME: fintech
      PORT: 5432
    
    ports:
      - "3000:5000"
volumes:
  postgres_data: null 
  pgadmin_data: null

