networks:
  demo:
    driver: bridge
    external: true
services:
  postgres:
    # conrtainer_name: nestjs1
    image: postgres:17
    networks:
      - demo
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sangduong
      POSTGRES_DB: fintech
      POSTGRES_PASSWORD: 210919
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes: 
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    container_name: pg_admin4
    image: dpage/pgadmin4
    networks:
      - demo
    restart: always
    ports:
      - "5050:8000"
    environment:
      PGADMIN_DEFAULT_EMAIL: sangdev219@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: 210919
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin 


  nestjs:
    # conrtainer_name: nestjs3
    image: nestjs:latest
    build: .
    networks:
      - demo
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: sangduong
      DB_PASS: 210919
      DB_NAME: fintech
      PORT: 5432
    
    ports:
      - "3000:5000"
volumes:
  postgres_data: null 
  pgadmin_data: null

